### ISSUE TITLE
Usage of the this data

### ISSUE THREAD

**Issue by sunithak** [antoine-lemay/Modbus_dataset#2]
Hello, I would like use this data in my project. I am not able to convert pcap files into csv without column names. When i am using tshark, i am not reading column field names. How should i read pcap file in csv? Thank you.

**Comment by antoine-lemay** [comment]
Hi, 
To fully answer your question, I would need more information about the specific tshark setup you are using as the syntax may vary from version to version and some information may be decoded (or not) depending on the protocols that are enabled for decoding.

However, since this is a question specifically for tshark, I think your odds for getting a swift answer is better on the Wireshark forums. The thread below provides good examples for saving pcap data in CSV format :
https://ask.wireshark.org/questions/2935/creating-a-csv-file-with-tshark

Also, you can use tshark -h to get the tshark help.

Good luck
Antoine

**Comment by sunithak** [comment]
Thank you very much for the help. It worked. I got csv files. My project is on the Graph based anomaly detection by using Machine learning algorithms. I know python and R. I dont know how to use this data in the way of finding anomalies. Could you guide me please? Thank you.

**Comment by antoine-lemay** [comment]
Well... I can't do your project for you. However, if this can give you a head start, you can either make use of the fact that the data is accompanied by labels to do supervised machine learning, or you can use unsupervised machine learning and use the labels as ground truth.

For supervised machine learning, you extract whatever feature you think appropriate with tshark and match the labels with the feature using the packet number (first column of the CSV). The 0 label represents a non malicious packet and the 1 label represent a malicious packet.

For unsupervised machine learning, you can create the classifier that you want and then verify your error rate by comparing the label provided by the algorithm with the label from the ground truth, matching them again by packet number. You can then calculate your error rate.

I hope this help and good luck in your project.

**Comment by sunithak** [comment]
Thank you very much for the help
